env: marine_env

env_args:
  map_name: "MarineNav" # others can be found in magent.py
  max_timesteps: 1000
  seed: 42
  schedule:
    timesteps: [0,1000000,2000000,3000000,4000000,5000000]
    num_cooperative: [3,5,7,7,7,7]
    num_non_cooperative: [0,0,0,0,0,0]
    num_cores: [4,6,8,8,8,8]
    num_obstacles: [0,0,0,6,8,10]
    min_start_goal_dis: [30.0,35.0,40.0,40.0,40.0,40.0]

mask_flag: False
global_state_flag: True
opp_action_in_cc: True
agent_level_batch_update: False